language: python
cache: pip
python:
  - "3.6"
install:
  - pip install tox-travis coverage coveralls
  - pip install -e .
script:
  - tox
  - coverage run --source=pkg -m pytest
  - coverage report -m
after_success:
  - coveralls
